Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M3_Y_COMP/PyAF_M3_Y_COMP_N107_6.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M3_Y_COMP/PyAF_M3_Y_COMP_N107_6.log' mode='a' encoding='UTF-8'>
BENCH_DATA M3_Y_COMP
TIME :  Date N= 14 H= 6 HEAD= [0 1 2 3 4] TAIL= [ 9 10 11 12 13]
SIGNAL :  N123 N= 14 H= 6 HEAD= [ 1397.    1561.8   1847.7   2154.55  2913.3 ] TAIL= [ 4965.  4990.   405.  5040.  5225.]
Index     N123  Date
1      1397.00     0
2      1561.80     1
3      1847.70     2
4      2154.55     3
5      2913.30     4
<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 1 to 14
Data columns (total 2 columns):
N123    14 non-null float64
Date    14 non-null int64
dtypes: float64(1), int64(1)
memory usage: 336.0+ bytes
None
SCIKIT_MODEL_FEATURE_SELECTION_FAILURE RelDiff_N123_ConstantTrend_residue_zeroCycle_residue_AR(3) (14, 3) divide by zero encountered in true_divide
BENCHMARK_FAILURE 'M3_Y_COMP_N123_6'
