Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_DEMOGRAPHICS/PyAF_M4_COMP_DEMOGRAPHICS_D0755_6.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_DEMOGRAPHICS/PyAF_M4_COMP_DEMOGRAPHICS_D0755_6.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_DEMOGRAPHICS
TIME :  Date N= 19 H= 6 HEAD= [0 1 2 3 4] TAIL= [14 15 16 17 18]
SIGNAL :  D0771 N= 19 H= 6 HEAD= [ 247.  254.  261.  267.  274.] TAIL= [ 299.  301.  216.  199.  289.]
   D0771  Date
0  247.0     0
1  254.0     1
2  261.0     2
3  267.0     3
4  274.0     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 19 entries, 0 to 18
Data columns (total 2 columns):
D0771    19 non-null float64
Date     19 non-null int64
dtypes: float64(1), int64(1)
memory usage: 456.0 bytes
None
SCIKIT_MODEL_FEATURE_SELECTION_FAILURE RelDiff_D0771_ConstantTrend_residue_zeroCycle_residue_AR(4) (19, 4) divide by zero encountered in true_divide
BENCHMARK_FAILURE 'M4_COMP_DEMOGRAPHICS_D0771_6'
