Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_DEMOGRAPHICS/PyAF_M4_COMP_DEMOGRAPHICS_D0098_6.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_DEMOGRAPHICS/PyAF_M4_COMP_DEMOGRAPHICS_D0098_6.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_DEMOGRAPHICS
TIME :  Date N= 27 H= 6 HEAD= [0 1 2 3 4] TAIL= [22 23 24 25 26]
SIGNAL :  D0125 N= 27 H= 6 HEAD= [ 11.  10.  10.   9.   9.] TAIL= [-110.  -17.  -31.  -38.   -4.]
   D0125  Date
0   11.0     0
1   10.0     1
2   10.0     2
3    9.0     3
4    9.0     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 27 entries, 0 to 26
Data columns (total 2 columns):
D0125    27 non-null float64
Date     27 non-null int64
dtypes: float64(1), int64(1)
memory usage: 648.0 bytes
None
SCIKIT_MODEL_FEATURE_SELECTION_FAILURE RelDiff_D0125_ConstantTrend_residue_zeroCycle_residue_AR(6) (27, 6) invalid value encountered in sqrt
BENCHMARK_FAILURE 'M4_COMP_DEMOGRAPHICS_D0125_6'
